### ISSUE TITLE
[Bug]: after npm install package types aren't resolved

### ISSUE THREAD

**Issue by Xstasy** [falsepopsky/thetvdb#48] opened 2023-10-25 00:03 UTC
### Package version

0.4.0

### Description

![image](https://github.com/falsepopsky/thetvdb/assets/283593/a34692b1-cef7-4421-91c2-24bb8ab5dda1)

### Reproduction/example

npm install in vscode in svelte + vite environment

### Steps to reproduce

npm install @untidy/thetvdb

**Comment by falsepopsky** [comment] 2023-10-25 00:52
Hi, do you have a link to a repository where the types are not resolved?

I used one of the [templates](https://vitejs.dev/guide/#trying-vite-online) from vite, must exactly this one [svelte-ts](https://vite.new/svelte-ts) and added the following dependencies:

- `@untidy/thetvdb`
- `@types/node`

I don't have any problems with Visual Studio Code or even the types. You can find the full reproduction [here](https://stackblitz.com/edit/vitejs-vite-71tkx3). Also, please remember that if you plan to use this package, it's not specifically designed for client-side use because it will expose your token. It should be used in a server-side context.

**Comment by falsepopsky** [comment] 2023-11-02 03:51
Marking as solved due to the absence of responses from the author. If possible, please provide, and always provide, a reproduction example repository. Thank you in advance.

**Closed by falsepopsky** 2023-11-02 03:51 UTC
Labels: bug 🐛
